spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/eventuate
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.jdbc.Driver
eventuatelocal:
  kafka:
    bootstrap:
      servers: 192.168.99.100:9092
  zookeeper:
    connection:
      string: 192.168.99.100:2181
